Project
LeoKuD/Death-Valley pull request #5
Opened 2021-12-10 08:21 UTC by LeoKuD

**The project is completed.**

[Link](https://leokud.github.io/Death-Valley/)

2021-12-21 13:50 UTC, maximsan requested changes
Hello!
I left several comments. Please review and fix them. We discussed almost all of them on previous lessons. Let me know if you still have questions. Don't forget to answer on every comment. It will not be merged till we resolve all issues 😃 Let's make your app shine! 😉

2021-12-21 13:50 UTC, maximsan commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
Please do not commit `package.json` file without scripts. Update it.

2021-12-21 13:50 UTC, maximsan commented on package.json
> +  "description": "",
Add description to your project

2021-12-21 13:50 UTC, maximsan commented on package.json
> +  "author": "",
Don't be so shy and add an author. Don't leave empty props

2021-12-21 13:50 UTC, maximsan commented on script.js
> +const gallery = document.querySelector('.gallery');
Please add indentation between lines of code

2021-12-21 13:50 UTC, maximsan commented on script.js
> +    let bigImg = smallImg.slice(0, smallImg.indexOf('.web')) + 'big.webp';
why all these variables a created by using let inside a method ? do you constantly change them ? Please assign variable to const in global scope.

2021-12-21 13:50 UTC, maximsan commented on script.js
> +    document.body.style.overflow = 'hidden';
Please use class modifier for this according to BEM

2021-12-21 13:50 UTC, maximsan commented on script.js
> +        document.body.style.overflow = 'visible';
Please use class modifier for this according to BEM

2021-12-21 13:50 UTC, maximsan commented on script.js
> +let form = document.forms.form;
The same question. Why do you use let ? Please use simple selector or give specific name to your form if you access it by using document

2021-12-21 13:50 UTC, maximsan commented on script.js
> +form.onsubmit = function submit(e) {
use addEventListener

2021-12-21 13:50 UTC, maximsan commented on script.js
> +    .forEach((input) => console.log(input.name, ': ', input.value));
Please use template literals https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Template_literals

2021-12-21 13:50 UTC, maximsan commented on index.html
> +              <a href="#feedback" class="btn btn--primary"> CONTACT US </a>
Please use modifier according to BEM

2021-12-21 13:50 UTC, maximsan commented on index.html
> +      <!-- about-us -->
remove

2021-12-21 13:50 UTC, maximsan commented on index.html
> +          <div class="section-feedback__block section-feedback__block_left">
You should keep elements inside their block or fix you names.

2021-12-21 13:50 UTC, maximsan commented on index.html
> +                <div class="content-wrapper__item-dialog__name">
Please fix names according to BEM

2021-12-21 13:50 UTC, maximsan commented on index.html
> +                <div class="content-wrapper__item-dialog__name">
Please fix names according to BEM

2021-12-21 13:50 UTC, maximsan commented on index.html
> +                <div class="content-wrapper__item-dialog__name">
Please fix names according to BEM

2021-12-21 13:50 UTC, maximsan commented on index.html
> +                <div class="content-wrapper__item-dialog__name">
Please fix names according to BEM

2021-12-21 13:50 UTC, maximsan commented on index.html
> +                <div class="content-wrapper__item-dialog__name">
Please fix names according to BEM

2021-12-21 13:50 UTC, maximsan commented on index.html
> +                <div class="content-wrapper__item-dialog__name">
Please fix names according to BEM

2021-12-21 13:50 UTC, maximsan commented on index.html
> +        <a name="feedback"></a>
Is it your anchor? It's more semantically obvious to use id instead of name. You don't need a separate element for this, add it to your next div tag

2021-12-21 13:50 UTC, maximsan commented on index.html
> +          <div class="content-about-us-wrapper">
Please use simpler name

2021-12-21 13:50 UTC, maximsan commented on index.html
> +                SH<span class="logo-wrapper__logo-text_letter-o">O</span>PNO
`_letter-o` is wrong name for modifier, please check docs.

2021-12-21 13:50 UTC, maximsan commented on scss/style.scss
> +}
it's not good place to use mixins, use variables

2021-12-21 13:50 UTC, maximsan commented on scss/style.scss
> +$color_2: rgba(255, 255, 255, 0.6);
Please use proper names

2021-12-21 13:50 UTC, maximsan commented on scss/style.scss
> +  // content-visibility: auto;
remove

2021-12-21 13:50 UTC, maximsan commented on scss/style.scss
> +      color: white;
it's still better to create a variable

2021-12-21 13:50 UTC, maximsan commented on scss/style.scss
> +  width: fit-content;
Please don't use it. It has bad support https://caniuse.com/?search=fit-content

2021-12-21 13:50 UTC, maximsan commented on scss/style.scss
> +    box-sizing: border-box;
don't need to use it, apply once at the begging to the whole project

2021-12-21 13:50 UTC, maximsan commented on scss/style.scss
> +          fill: #000;
create variable

2021-12-21 13:50 UTC, maximsan commented on scss/style.scss
> +      background-color: #8d8d8d;
create variable

2021-12-23 06:57 UTC, LeoKuD commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
```
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "gulp watch"
  },
```

2021-12-23 06:58 UTC, LeoKuD commented on package.json
> +  "description": "",
```
 {
  "name": "death-valley",
  "version": "1.0.0",
  "description": "DEV Incubator Project",
```

2021-12-23 06:59 UTC, LeoKuD commented on package.json
> +  "author": "",
```
  },
  "author": "Evgeniy Moroz (@leokud)",
  "license": "ISC",
```

2021-12-23 07:14 UTC, LeoKuD commented on script.js
> +let form = document.forms.form;
`const formFeedback = document.forms.form;
`

2021-12-23 07:22 UTC, LeoKuD commented on script.js
> +form.onsubmit = function submit(e) {
```
document.forms.form.addEventListener('submit', (e) => {
  e.preventDefault();
  document
    .querySelectorAll('input')
    .forEach((input) => console.log(`${input.name} : ${input.value}`));
})
```

2021-12-23 07:22 UTC, LeoKuD commented on script.js
> +    .forEach((input) => console.log(input.name, ': ', input.value));
```
  document
    .querySelectorAll('input')
    .forEach((input) => console.log(`${input.name} : ${input.value}`));
})
```

2021-12-23 07:25 UTC, LeoKuD commented on index.html
> +      <!-- about-us -->
Fixed

2021-12-23 07:27 UTC, LeoKuD commented on index.html
> +        <a name="feedback"></a>
```
      <section class="section-outer section-feedback">
        <div id="feedback" class="section-inner">
```

2021-12-23 07:43 UTC, LeoKuD commented on scss/style.scss
> +}
```
$ff-Merriweather: 'Merriweather', serif;
$ff-Montserrat: 'Montserrat', serif;
$ff-Raleway: 'Raleway', sans-serif;
```

2021-12-23 07:46 UTC, LeoKuD commented on scss/style.scss
> +$color_2: rgba(255, 255, 255, 0.6);
```
$color-primary: #6df6eb;
$color-secondary: rgba(255, 255, 255, 0.6);
```

2021-12-23 07:47 UTC, LeoKuD commented on scss/style.scss
> +  // content-visibility: auto;
Fixed

2021-12-23 07:57 UTC, LeoKuD commented on scss/style.scss
> +      color: white;
&:hover {
      background-color: $fc-secondary;
      color: $hover-color-primary;
    }

2021-12-23 08:05 UTC, LeoKuD commented on scss/style.scss
> +  width: fit-content;
Fixed

2021-12-23 08:10 UTC, LeoKuD commented on scss/style.scss
> +    box-sizing: border-box;
```
.section-header {
  background-color: $bc-header;
  min-height: 100vh;
  padding-top: 6%;
}
```

2021-12-23 08:12 UTC, LeoKuD commented on scss/style.scss
> +    box-sizing: border-box;
html {
  scroll-behavior: smooth;
  box-sizing: border-box;
}

2021-12-23 08:15 UTC, LeoKuD commented on scss/style.scss
> +          fill: #000;
```
        svg {
          fill: $hover-color-primary;
          stroke: $color-secondary;
        }
```

2021-12-23 08:17 UTC, LeoKuD commented on scss/style.scss
> +      background-color: #8d8d8d;
```
      width: 2.813rem;
      height: 2.5rem;
      background-color: $bc-primary;
```

2021-12-23 08:23 UTC, LeoKuD commented on index.html
> +                SH<span class="logo-wrapper__logo-text_letter-o">O</span>PNO
```
              <h5 class="logo-wrapper__logo-text">
                SH<span class="logo-wrapper__logo-text_big-letter">O</span>PNO
              </h5>
```

2021-12-23 08:31 UTC, LeoKuD commented on index.html
> +          <div class="content-about-us-wrapper">
```
        <div class="section-inner">
          <h2>ABOUT US</h2>
          <h4>LOREM IPSUM DOLOR SIT AMET EVENT LANDING TEMPLATE</h4>
          <div class="about-us">
            <div class="about-us__image">
```

2021-12-23 08:40 UTC, LeoKuD commented on index.html
> +                <div class="content-wrapper__item-dialog__name">
```
              <div class="dialog">
                <div class="dialog__name">
                  <h3>AL RAYHAN</h3>
                  <h5>/ UI Designer</h5>
```

2021-12-23 08:41 UTC, LeoKuD commented on index.html
> +                <div class="content-wrapper__item-dialog__name">
```
              <div class="dialog">
                <div class="dialog__name">
                  <h3>AL RAYHAN</h3>
                  <h5>/ UI Designer</h5>
```

2021-12-23 08:41 UTC, LeoKuD commented on index.html
> +                <div class="content-wrapper__item-dialog__name">
```
              <div class="dialog">
                <div class="dialog__name">
                  <h3>AL RAYHAN</h3>
                  <h5>/ UI Designer</h5>
```

2021-12-23 08:54 UTC, LeoKuD commented on index.html
> +                <div class="content-wrapper__item-dialog__name">
```
            <div loading="lazy" class="team-item">
              <img width="370px" height="440px" src="img/team-4.webp" alt="#" />
              <div class="dialog">
                <div class="dialog__name">
```

2021-12-23 08:54 UTC, LeoKuD commented on index.html
> +                <div class="content-wrapper__item-dialog__name">
[            <div loading="lazy" class="team-item">
              <img width="370px" height="440px" src="img/team-4.webp" alt="#" />
              <div class="dialog">
                <div class="dialog__name">](url)

2021-12-23 08:56 UTC, LeoKuD commented on index.html
> +                <div class="content-wrapper__item-dialog__name">
```
                alt="#"
              />
              <div class="dialog">
                <div class="dialog__name">
```

2021-12-23 09:08 UTC, LeoKuD commented on index.html
> +          <div class="section-feedback__block section-feedback__block_left">
```
      <section class="section-outer section-feedback">
        <div id="feedback" class="section-inner">
          <div class="feedback-block block-left">
```

2021-12-23 09:10 UTC, LeoKuD commented on index.html
> +              <a href="#feedback" class="btn btn--primary"> CONTACT US </a>
```
          </div>
          <div class="btn">
            <div class="btn-wrapper">
              <a href="#feedback" class="btn btn_primary"> CONTACT US </a>
```

2021-12-23 09:11 UTC, LeoKuD commented on script.js
> +let form = document.forms.form;
```

document.forms.form.addEventListener('submit', (e) => {
  e.preventDefault();
  document
    .querySelectorAll('input')
    .forEach((input) => console.log(`${input.name} : ${input.value}`));
})
```

2021-12-23 09:11 UTC, LeoKuD commented on script.js
> +    let bigImg = smallImg.slice(0, smallImg.indexOf('.web')) + 'big.webp';
```
const gallery = document.querySelector('.gallery');
const img = document.querySelector('.popup img');
const popup = document.querySelector('.popup');

```

2021-12-23 09:12 UTC, LeoKuD commented on script.js
> +const gallery = document.querySelector('.gallery');
Fixed

2021-12-23 09:45 UTC, LeoKuD commented on script.js
> +        document.body.style.overflow = 'visible';
```
gallery.addEventListener('click', ({target}) => {
  if (target.tagName === 'IMG') {
    img.src = target.getAttribute('src');
    body.classList.add('overflow-hidden');
    popup.classList.add('display-block');
  }
});
popup.addEventListener('click', ({target}) => {
  if (target.tagName !== 'IMG') {
    popup.classList.remove('display-block')
    body.classList.remove('overflow-hidden');
  }
});
```

2021-12-23 09:49 UTC, LeoKuD commented on script.js
> +    document.body.style.overflow = 'hidden';
I removed the code with the replacement of the picture

2021-12-23 17:17 UTC, maximsan commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
Please remove also useless test script.

2021-12-23 17:20 UTC, maximsan commented on scss/style.scss
> +  width: fit-content;
Please don't forget to provide a preview of code with you fix by using ```suggestion``` for example. It's mentioned in the rules on our discord server 😄

2021-12-23 17:21 UTC, maximsan commented on scss/style.scss
> +    box-sizing: border-box;
It's better to apply it by using `*` selector

2021-12-27 18:30 UTC, maximsan requested changes
Hello! Did you ever use validator - https://validator.w3.org/ ? Please check that you do everything according to task description https://github.com/Dev-incubator/fe-death-valley and then submit you pr. Fix everything and let me know.

2021-12-27 18:30 UTC, maximsan commented on index.html
> +    <header class="section-outer section-header">
You use class names wrongly here. You have 2 blocks at the same level but as I see you can't use them separately. So as a conclusion You should use `section-outer` as a block and `section-header` as a modifier but with correct names. Don't overcomplicate names. Don't use `section...` part.

2021-12-27 18:30 UTC, maximsan commented on index.html
> +              <h1 class="header-text-wrapper__text">
Please make your names simpler!

2021-12-27 18:30 UTC, maximsan commented on index.html
> +                SH<span class="logo-wrapper__logo-text_big-letter">O</span>PNO
According to BEM it should be `logo-wrapper__logo-text logo-wrapper__logo-text_big-letter`

2021-12-27 18:30 UTC, maximsan commented on index.html
> +          <div class="logo-wrapper">
Why do you need 2 divs here? It can be accomplished by using 1 div.

2021-12-27 18:30 UTC, maximsan commented on index.html
> +            <div class="header-text-wrapper">
Here is the same question. Why do you need 2 divs here? It can be accomplished by using 1 div.

2021-12-27 18:30 UTC, maximsan commented on index.html
> +          <div class="btn">
BTW Why it's named liked `btn` ?

2021-12-27 18:30 UTC, maximsan commented on index.html
> +              <a href="#feedback" class="btn btn_primary"> CONTACT US </a>
Why do you have block again inside element if you have it outside in div. You do it in wrong way!

2021-12-27 18:30 UTC, maximsan commented on index.html
> +      <section class="section-outer section-about-us">
Please fix classes here too

2021-12-27 18:30 UTC, maximsan commented on index.html
> +        <div class="section-inner">
Please fix classes here too

2021-12-27 18:30 UTC, maximsan commented on index.html
> +              alt="text"
'Alt' should be different and meaningful everywhere, because browser uses it for crawling and accessibility

2021-12-27 18:30 UTC, maximsan commented on index.html
> +                alt=""
Write the text inside! 'Alt' should be different and meaningful everywhere, because browser uses it for crawling and accessibility

2021-12-27 18:30 UTC, maximsan commented on index.html
> +                alt="#"
Write the text inside! 'Alt' should be different and meaningful everywhere, because browser uses it for crawling and accessibility

2021-12-27 18:30 UTC, maximsan commented on index.html
> +                alt="#"
Write the text inside! 'Alt' should be different and meaningful everywhere, because browser uses it for crawling and accessibility

2021-12-27 18:30 UTC, maximsan commented on index.html
> +              <img width="370px" height="440px" src="img/team-4.webp" alt="#" />
Write the text inside! 'Alt' should be different and meaningful everywhere, because browser uses it for crawling and accessibility

2021-12-31 06:33 UTC, LeoKuD commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
```
 "scripts": {
    "start": "gulp watch"
  },
```

2021-12-31 06:41 UTC, LeoKuD commented on scss/style.scss
> +  width: fit-content;
```
.section-header {
  background-color: $bc-header;
  min-height: 100vh;
  padding-top: 6%;
}

.wrapper-header-content {
  margin: 0 auto;
  text-align: center;
  margin-top: 17%;

  .btn {
    margin-top: 15%;
  }
}
```
I removed fit-content.

2021-12-31 06:44 UTC, LeoKuD commented on scss/style.scss
> +    box-sizing: border-box;
```
* {
  box-sizing: border-box;
  font-family: $ff-Raleway;
  scroll-behavior: smooth;
}
```

2021-12-31 06:52 UTC, LeoKuD commented on scss/style.scss
> +    font-size: 1.75rem;
```
$fs-h1: 2.813rem;
$fs-h2: 2.375rem;
$fs-h3: 1.25rem;
$fs-h4: 1.125rem;
$fs-h5: 1.063rem;
$fs-h6: 1rem;
```

2021-12-31 07:04 UTC, LeoKuD commented on index.html
> +              <img width="370px" height="440px" src="img/team-4.webp" alt="#" />
```
            <div loading="lazy" class="team-item">
              <img width="370px" height="440px" src="img/team-4.webp" alt="Profession - Name 4" />
```

2021-12-31 07:04 UTC, LeoKuD commented on index.html
> +                alt="#"
```
              <img
                loading="lazy"
                width="370px"
                height="440px"
                src="img/team-3.webp"
                alt="Profession - Name 3"
              />
```

2021-12-31 07:04 UTC, LeoKuD commented on index.html
> +                alt="#"
```
              <img
                loading="lazy"
                width="370px"
                height="440px"
                src="img/team-2.webp"
                alt="Profession - Name 2"
              />
```

2021-12-31 07:05 UTC, LeoKuD commented on index.html
> +                alt=""
```
              <img
                loading="lazy"
                width="370px"
                height="440px"
                src="img/team-1.webp"
                alt="Profession - Name 1"
              />
```

2021-12-31 07:12 UTC, LeoKuD commented on index.html
> +              alt="text"
```
            <img
              loading="lazy"
              width="370px"
              height="359px"
              class="team-item"
              src="img/work-1.webp"
              alt="design project - ice cream"
            />
            <img
              loading="lazy"
              width="370px"
              height="359px"
              class="team-item"
              src="img/work-2.webp"
              alt="design project - business card"
            />
            <img
              loading="lazy"
              width="370px"
              height="359px"
              class="team-item"
              src="img/work-3.webp"
              alt="design project - bottle logo"
            />
```

2021-12-31 13:49 UTC, maximsan commented on index.html
> +              alt="text"
It's ok now 👍🏻

2022-01-03 08:19 UTC, LeoKuD commented on index.html
> +                SH<span class="logo-wrapper__logo-text_big-letter">O</span>PNO
```
            <a class="logo-wrapper__logo-link" href="#">
              <h5 class="logo-wrapper__logo-text">
                SH<span class="logo-wrapper__logo-text logo-wrapper__logo-text_big-letter">O</span>PNO
              </h5>
            </a>
```

2022-01-03 09:01 UTC, LeoKuD commented on index.html
> +              <h1 class="header-text-wrapper__text">
```
        <div class="header-content">
          <div class="header-content__wrapper">
            <h1 class="header-content__text">
              SAY HELLO TO
              <span class="header-content__text header-content__text-selected"> SHOPNO!</span>
              <br />
              <span class="header-content__text header-content__text-selected-last"
                >AGENCY
              </span>
              CORPORATE SHOPNO THEME
            </h1>
          </div>
```

2022-01-03 09:55 UTC, LeoKuD commented on script.js
> +    popup.classList.add('display-block');
```
  if (target.tagName === 'IMG') {
    img.src = target.getAttribute('src');
    body.classList.add('overflow');
    popup.classList.add('popup_visible');
  }
```

2022-01-03 11:52 UTC, LeoKuD commented on index.html
> +    <header class="section-outer section-header">
```
    <header class="outer outer_header">
      <div class="inner">
```

Fixed all section names

2022-01-03 12:05 UTC, LeoKuD commented on index.html
> +          <div class="logo-wrapper">
```
    <header class="outer outer_header">
      <div class="inner">
          <div class="logo">
            <a class="logo__link" href="#">
              <h5 class="logo__text">
                SH<span class="logo__text logo__text_big-letter">O</span>PNO
              </h5>
            </a>
        </div>
```

2022-01-03 12:12 UTC, LeoKuD commented on index.html
> +            <div class="header-text-wrapper">
```
        </div>
        <div class="header-content">
            <h1 class="header-content__text">
              SAY HELLO TO
```

2022-01-03 12:14 UTC, LeoKuD commented on index.html
> +              <h1 class="header-text-wrapper__text">
```
        <div class="header-content">
            <h1 class="header-content__text">
              SAY HELLO TO
```

2022-01-03 12:34 UTC, LeoKuD commented on index.html
> +          <div class="btn">
```
            </h1>
          <div class="header-content__btn-contacts">
```

2022-01-03 12:35 UTC, LeoKuD commented on index.html
> +              <a href="#feedback" class="btn btn_primary"> CONTACT US </a>
</h1>
          <div class="header-content__btn-contacts">
              <a href="#feedback" class="btn btn_primary"> CONTACT US </a>
          </div>

2022-01-03 12:36 UTC, LeoKuD commented on index.html
> +      <section class="section-outer section-about-us">
```
    <main>
      <section class="outer outer_about-us">
        <div class="inner">
```

2022-01-03 12:36 UTC, LeoKuD commented on index.html
> +        <div class="section-inner">
```
      <section class="outer outer_featured-works">
        <div class="inner">
```

2022-01-09 09:01 UTC, maximsan approved these changes
Hello. It's better. I left minor notes, please look them through. I also want you to pay attention that you markup after approximately 1444px  has gaps on the left and right sides of background. I'd rather recommend to remove it. It looks weird. At 720, 540 break-points the section `about us` has very small image and not align text with big font-size. I also recommend you to fix it. In general it's a good work 🚀

2022-01-10 06:18 UTC, LeoKuD commented on index.html
> +              <span class="header-content__text header-content__text-selected-last"
```suggestion
              <span class="header-content__text header-content__text-selected-last"
```

2022-01-10 06:18 UTC, LeoKuD commented on index.html
> +              <span class="header-content__text header-content__text-selected-last"
```suggestion
                        <h1 class="header-content__text">
            SAY HELLO TO
            <span class="header-content__text header-content__text_selected">
              SHOPNO!</span
            >
            <br />
            <span
              class="header-content__text header-content__text_selected-last"
              >AGENCY
            </span>
            CORPORATE SHOPNO THEME
          </h1>
```

2022-01-10 06:19 UTC, LeoKuD commented on index.html
> +              <span class="header-content__text header-content__text-selected-last"
```suggestion
              <span class="header-content__text header-content__text_selected-last"
```

2022-01-10 06:21 UTC, LeoKuD commented on index.html
> +              <span class="header-content__text header-content__text-selected"> SHOPNO!</span>
```suggestion
              <span class="header-content__text header-content__text_selected"> SHOPNO!</span>
```

2022-01-10 07:12 UTC, LeoKuD commented on scss/style.scss
> +        font-size: 1.125rem;
```
      h3 {
        font-size: $fs-h4;
      }
```

2022-01-10 07:13 UTC, LeoKuD commented on scss/style.scss
> +        font-size: 0.875rem;
```
    .block-right {
      h5 {
        font-size: $fs-small;
      }
```

2022-01-10 07:13 UTC, LeoKuD commented on scss/style.scss
> +    font-size: 1.75rem;
```
@media (max-width: 33.75em) {
  h1 {
    font-size: $fs-large;
```

2022-01-10 22:42 UTC, maximsan approved these changes
Approved from my side. You need to get another one. Good work!

2022-01-11 16:13 UTC, Dev1LtJ commented on scss/style.scss
> +  letter-spacing: 2.16px;
Round up it

2022-01-11 16:13 UTC, Dev1LtJ commented on scss/style.scss
> +  margin: 7.813rem 0;
Round up it

2022-01-11 16:14 UTC, Dev1LtJ commented on scss/style.scss
> +      font-size: 1.313rem;
Round up it

2022-01-11 16:15 UTC, Dev1LtJ commented on scss/style.scss
> +        top: -1.563rem;
Round up it

2022-01-11 16:17 UTC, Dev1LtJ commented on scss/style.scss
> +  font-size: 0.938rem;
Round up it.

2022-01-11 16:17 UTC, Dev1LtJ commented on scss/style.scss
> +    padding-bottom: 8.438rem;
Round up it.

2022-01-11 16:18 UTC, Dev1LtJ commented on scss/style.scss
> +      width: 2.813rem;
Round up it.

2022-01-11 16:18 UTC, Dev1LtJ commented on scss/style.scss
> +          font-size: 0.938rem;
Round up it.

2022-01-11 16:18 UTC, Dev1LtJ commented on scss/style.scss
> +          font-size: 0.938rem;
Round up it.

2022-01-11 16:18 UTC, Dev1LtJ commented on scss/style.scss
> +      padding: 2.188rem 0 0 0;
Round up it.

2022-01-11 16:18 UTC, Dev1LtJ commented on scss/style.scss
> +    font-size: 2.188rem;
Round up it.

2022-01-11 16:19 UTC, Dev1LtJ commented on scss/style.scss
> +    padding: 0.813rem 2.188rem;
Round up it.

2022-01-11 16:19 UTC, Dev1LtJ commented on scss/style.scss
> +        font-size: 0.938rem;
Round up it.

2022-01-11 16:21 UTC, Dev1LtJ commented on index.html
> +    <link rel="shortcut icon" href="./img/favicon.ico"image/x-icon">
type="image/x-icon"

2022-01-11 16:21 UTC, Dev1LtJ commented on index.html
> +              height="85px"
use css

2022-01-11 16:24 UTC, Dev1LtJ commented on index.html
> +          <div class="content-wrapper gallery">
content-wrapper_gallery

2022-01-11 16:24 UTC, Dev1LtJ commented on index.html
> +              class="team-item"
This is not BEM

2022-01-11 16:25 UTC, Dev1LtJ commented on index.html
> +            <div class="team-item">
team__item

2022-01-11 16:27 UTC, Dev1LtJ commented on index.html
> +          <div class="feedback-block block-left">
feedback__block (rename block) feedback__block_left

2022-01-11 16:27 UTC, Dev1LtJ commented on index.html
> +          <div class="feedback-block block-right">
feedback__block feedback__block_right

2022-01-11 16:28 UTC, Dev1LtJ commented on index.html
> +            <a href="tel: +45645654546"><h5>Fax: +456456 54546</h5></a>
You don't need `h5` here

2022-01-11 16:28 UTC, Dev1LtJ commented on index.html
> +            >
You don't need `h5` here

2022-01-11 16:29 UTC, Dev1LtJ commented on index.html
> +    <footer class="footer">
Do you have more than one footer on your page?

2022-01-12 04:51 UTC, LeoKuD commented on scss/style.scss
> +  padding: 0.813rem 2.813rem;
```suggestion
  padding: 0.8rem 2.8rem;
```

2022-01-12 04:53 UTC, LeoKuD commented on scss/style.scss
> +  margin-top: 2.188rem;
```suggestion
   margin-top: 2.2rem;
```

2022-01-12 04:54 UTC, LeoKuD commented on scss/style.scss
> +$fs-h1: 2.813rem;
```suggestion
$fs-h1: 2.8rem;
```

2022-01-12 04:56 UTC, LeoKuD commented on scss/style.scss
> +$fs-h5: 1.063rem;
```suggestion
$fs-h1: 2.8rem;
$fs-h2: 2.4rem;
$fs-h3: 1.3rem;
$fs-h4: 1.1rem;
$fs-h5: 1rem;
$fs-h6: 1rem;
$fs-small: 0.9rem;
$fs-large: 1.8rem;
```

2022-01-12 04:57 UTC, LeoKuD commented on scss/style.scss
> +  letter-spacing: 2.16px;
```suggestion
  letter-spacing: 2.2px;
```

2022-01-12 04:58 UTC, LeoKuD commented on scss/style.scss
> +    padding: 1.25rem 2.313rem;
```suggestion
    padding: 1.3rem 2.3rem;
```

2022-01-12 04:58 UTC, LeoKuD commented on scss/style.scss
> +  margin: 7.813rem 0;
```suggestion
  margin: 7.8rem 0;
```

2022-01-12 04:59 UTC, LeoKuD commented on scss/style.scss
> +  height: 2.813rem;
```suggestion
  width: 7.2rem;
  height: 2.8rem;
```

2022-01-12 04:59 UTC, LeoKuD commented on scss/style.scss
> +      font-size: 1.313rem;
```suggestion
      font-size: 1.3rem;
```

2022-01-12 05:00 UTC, LeoKuD commented on scss/style.scss
> +    padding: 0 0.938rem;
```suggestion
    padding: 0 0.9rem;
```

2022-01-12 05:00 UTC, LeoKuD commented on scss/style.scss
> +      padding: 0 0 0 0.938rem;
```suggestion
      padding: 0 0 0 0.9rem;
```

2022-01-12 05:00 UTC, LeoKuD commented on scss/style.scss
> +      margin-right: 0.313rem;
```suggestion
      margin-right: 0.3rem;
```

2022-01-12 05:01 UTC, LeoKuD commented on scss/style.scss
> +    padding-bottom: 10.313rem;
```suggestion
    margin-top: 9.1rem;
    padding-bottom: 10rem;
```

2022-01-12 05:02 UTC, LeoKuD commented on scss/style.scss
> +      margin-left: 2.813rem;
```suggestion
      margin-left: 2.8rem;
```

2022-01-12 05:02 UTC, LeoKuD commented on scss/style.scss
> +        margin-top: 1.563rem;
```suggestion
        margin-top: 1.6rem;
```

2022-01-12 05:08 UTC, LeoKuD commented on scss/style.scss
> +        top: -1.563rem;
```suggestion
        top: -1.6rem;
```

2022-01-12 05:08 UTC, LeoKuD commented on scss/style.scss
> +        border-width: 0.625rem 0.938rem;
```suggestion
        border-width: 0.6rem 0.9rem;
```

2022-01-12 05:08 UTC, LeoKuD commented on scss/style.scss
> +      font-size: 0.938rem;
```suggestion
      font-size: 0.9rem;
```

2022-01-12 05:09 UTC, LeoKuD commented on scss/style.scss
> +      margin: 0.375rem 0.625rem 0px 0.313rem;
```suggestion
      margin: 0.8rem 0.6rem 0px 0.3rem;
```

2022-01-12 05:09 UTC, LeoKuD commented on scss/style.scss
> +          margin-top: 0.938rem;
```suggestion
          margin-top: 0.9rem;
```

2022-01-12 05:09 UTC, LeoKuD commented on scss/style.scss
> +  font-size: 0.938rem;
```suggestion
  font-size: 0.9rem;
```

2022-01-12 05:10 UTC, LeoKuD commented on scss/style.scss
> +  margin-top: 1.563rem;
```suggestion
  margin-top: 1.6rem;
```

2022-01-12 05:10 UTC, LeoKuD commented on scss/style.scss
> +    padding-bottom: 8.438rem;
```suggestion
    padding-bottom: 8.4rem;
```

2022-01-12 05:10 UTC, LeoKuD commented on scss/style.scss
> +    padding: 5.313rem 0 0 0;
```suggestion
    padding: 5.3rem 0 0 0;
```

2022-01-12 05:11 UTC, LeoKuD commented on scss/style.scss
> +      width: 2.813rem;
```suggestion
      width: 2.8rem;
```

2022-01-12 05:11 UTC, LeoKuD commented on scss/style.scss
> +        padding: 0 0.938rem;
```suggestion
        padding: 0 0.9rem;
```

2022-01-12 05:12 UTC, LeoKuD commented on scss/style.scss
> +          font-size: 0.938rem;
```suggestion
          font-size: 0.9rem;
```

2022-01-12 05:12 UTC, LeoKuD commented on scss/style.scss
> +          font-size: 0.938rem;
```suggestion
          font-size: 0.9rem;
```

2022-01-12 05:15 UTC, LeoKuD commented on scss/style.scss
> +      padding-bottom: 2.188rem;
```suggestion
      padding-bottom: 2.2rem;
```

2022-01-12 05:15 UTC, LeoKuD commented on scss/style.scss
> +      padding: 2.188rem 0 0 0;
```suggestion
      padding: 2.2rem 0 0 0;
```

2022-01-12 05:15 UTC, LeoKuD commented on scss/style.scss
> +    font-size: 2.188rem;
```suggestion
    font-size: 2.2rem;
```

2022-01-12 05:15 UTC, LeoKuD commented on scss/style.scss
> +          font-size: 0.938rem;
```suggestion
          font-size: 0.9rem;
```

2022-01-12 05:15 UTC, LeoKuD commented on scss/style.scss
> +    padding: 0.813rem 2.188rem;
```suggestion
    padding: 0.813rem 2.2rem;
```

2022-01-12 05:16 UTC, LeoKuD commented on scss/style.scss
> +        font-size: 0.938rem;
```suggestion
        font-size: 0.9rem;
```

2022-01-12 05:18 UTC, LeoKuD commented on index.html
> +    <title>Death Vallye Part 1</title>
```suggestion
    <title>Creation of a design to order</title>
```

2022-01-12 05:20 UTC, LeoKuD commented on index.html
> +    <link rel="shortcut icon" href="./img/favicon.ico"image/x-icon">
```suggestion
    <link rel="shortcut icon" href="./img/favicon.ico" type="image/x-icon">
```

2022-01-12 05:21 UTC, LeoKuD commented on index.html
> +              height="85px"
```suggestion

```

2022-01-12 05:21 UTC, LeoKuD commented on index.html
> +                height="483px"
```suggestion
```

2022-01-12 05:29 UTC, LeoKuD commented on index.html
> +          <div class="content-wrapper gallery">
```suggestion
          <div class="content-wrapper">
```

2022-01-12 05:39 UTC, LeoKuD commented on index.html
> +              class="team-item"
```suggestion
              class="content-wrapper__team-item"
```

2022-01-12 05:44 UTC, LeoKuD commented on index.html
> +            <div class="team-item">
```suggestion
            <div class="team__item">
```

2022-01-12 05:56 UTC, LeoKuD commented on index.html
> +          <div class="feedback-block block-right">
```suggestion
          <div class="feedback__right">
```

2022-01-12 05:56 UTC, LeoKuD commented on index.html
> +          <div class="feedback-block block-left">
```suggestion
          <div class="feedback__left">
```

2022-01-12 05:57 UTC, LeoKuD commented on index.html
> +    <footer class="footer">
```suggestion
    <footer>
```

2022-01-12 06:14 UTC, LeoKuD commented on index.html
> +            <a href="tel: +45645654546"><h5>Fax: +456456 54546</h5></a>
```suggestion
            <p>Adress line 1</p>
            <p>Adress line 2</p>
            <p><a href="tel: +548945645">Phone: +548 945645</a></p>
            <p><a href="tel: +45645654546">Fax: +456456 54546</a></p>
```

2022-01-12 06:15 UTC, LeoKuD commented on index.html
> +            >
```suggestion
            <p><a href="www.designagency.net">Web: www.designagency.net</a></p>
            <p>
              <a href="mailto:info@designagency.net"
                >E-mail: info@designagency.net</a
              >
            </p>
```

2022-01-12 07:33 UTC, Dev1LtJ approved these changes
Approved. Good work.

2022-01-12 20:15 UTC, merged